# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# Available images and SDKs, simulators: https://github.com/actions/runner-images?tab=readme-ov-file

# For the terminal to test
# xcodebuild clean build test \
#   -project NASAGallery/NASAGallery.xcodeproj/ \
#   -scheme "NASAGallery" \
#   -sdk macosx14.2 \
#   -destination "platform=macOS,arch=arm64" \
#   -testPlan "CI" \
#   CODE_SIGN_IDENTITY="" \
#   CODE_SIGNING_REQUIRED=NO

name: CI-iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-15
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test iOS CI
      run: xcodebuild clean build test -project NASAGallery/NASAGallery.xcodeproj/ -scheme "CI" -sdk iphonesimulator18.2 -destination "platform=iOS Simulator,OS=18.2,name=iPhone 16" -testPlan "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
