# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# Available images and SDKs, simulators: https://github.com/actions/runner-images?tab=readme-ov-file

# For the terminal to test
# xcodebuild clean build test \
#   -project NASAGallery/NASAGallery.xcodeproj/ \
#   -scheme "NASAGallery" \
#   -sdk macosx14.2 \
#   -destination "platform=macOS,arch=arm64" \
#   -testPlan "CI" \
#   CODE_SIGN_IDENTITY="" \
#   CODE_SIGNING_REQUIRED=NO

# Note: runner reference:
# https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md

name: CI-iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-15
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Debug Simulator environment
      run: |
        echo "=== SDKs ==="
        /usr/bin/xcodebuild -showsdks
        echo
        echo "=== simctl runtimes ==="
        xcrun simctl list runtimes
        echo
        echo "=== simctl devices ==="
        xcrun simctl list devices
        echo
        echo "=== Destinations for CI-iOS ==="
        /usr/bin/xcodebuild -project NASAGallery/NASAGallery.xcodeproj \
                            -scheme "CI-iOS" \
                            -showdestinations || true

    - name: Build and Test CI iOS
      run: xcodebuild clean build test -project NASAGallery/NASAGallery.xcodeproj/ -scheme "CI-iOS" -sdk iphonesimulator18.5 -destination "platform=iOS Simulator,OS=18.5,name=iPhone 16" -testPlan "CI-iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
