# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# For the terminal to test
# xcodebuild clean build test \
#   -project NASAGallery/NASAGallery.xcodeproj/ \
#   -scheme "NASAGallery" \
#   -sdk macosx14.2 \
#   -destination "platform=macOS,arch=arm64" \
#   -testPlan "CI" \
#   CODE_SIGN_IDENTITY="" \
#   CODE_SIGNING_REQUIRED=NO

name: CI-macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-13
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Fix Xcode 15 slowness issues
      run: |
       wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
       sudo installer -pkg yeetd-normal.pkg -target /
       yeetd &

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.1.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test MacOS CI
      run: xcodebuild clean build test -project NASAGallery/NASAGallery.xcodeproj/ -scheme "NASAGallery" -sdk macosx14.2 -destination "platform=macOS,arch=arm64" -testPlan "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO